### ISSUE TITLE
create file upload api

### ISSUE THREAD

**Issue by obaid22192** [projectEP/test#29]
initially we we save all files in to the database until file storage server is up and running.

**Comment by obaid22192** [comment]
The deadline passed 3 days ago, we had to close this milestone, would you like to update team what is the current status of this issue?

**Comment by SantiRamRai** [comment]
Done: But i haven`t push it yet.

**Comment by obaid22192** [comment]
then why did you close the issue?

**Comment by SantiRamRai** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Now, I did push.


Sent from Yahoo Mail for iPhone


On Wednesday, June 15, 2016, 1:02 AM, obaid22192 <notifications@github.com> wrote:


then why did you close the issue?

**Comment by obaid22192** [comment]
What does this means?

**Comment by SantiRamRai** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Closed the issues and pushed the project.


Sent from Yahoo Mail for iPhone


On Wednesday, June 15, 2016, 1:13 AM, obaid22192 <notifications@github.com> wrote:


What does this means?

**Comment by SantiRamRai** [comment]
File upload API is done,

**Comment by SantiRamRai** [comment]
Error message "Unknown Error" When file upload:
![upload1](https://cloud.githubusercontent.com/assets/8695718/16417360/d4abc8c4-3d45-11e6-9bd5-c8a849cf3d8a.png)
![upload2](https://cloud.githubusercontent.com/assets/8695718/16417365/d7de4166-3d45-11e6-8c83-37dc67f873db.png)

**Comment by obaid22192** [comment]
It would be great if you add description along with your previous comment.

**Comment by obaid22192** [comment]
<form>
            Select csv file to upload:
            <input  type="file" onchange="angular.element(this).scope().fileChanged(this)">
            <md-button ng-click="submit()">
            upload
            </md-button>
        </form>

**Comment by obaid22192** [comment]
<form>
            Select csv file to upload:
            <input  type="file" onchange="angular.element(this).scope().fileChanged(this)">
            <md-button ng-click="submit()">
            upload
            </md-button>
        </form>

**Comment by obaid22192** [comment]
"<form>
            Select csv file to upload:
            <input  type="file" onchange="angular.element(this).scope().fileChanged(this)">
            <md-button ng-click="submit()">
            upload
            </md-button>
        </form>"

**Comment by obaid22192** [comment]
/<form>
            Select csv file to upload:
            <input  type="file" onchange="angular.element(this).scope().fileChanged(this)">
            <md-button ng-click="submit()">
            upload
            </md-button>
        </form>/

**Comment by obaid22192** [comment]
<input type="file" onchange="angular.element(this).scope().fileChanged(this)">

**Comment by obaid22192** [comment]
$scope.fileChanged = function(ele) {
      $scope.files = ele.files;
      $scope.$apply();
    }
