### ISSUE TITLE
add delete folder api.

### ISSUE THREAD

**Issue by obaid22192** [projectEP/test#34]

**Comment by obaid22192** [comment]
The deadline passed 3 days ago, we had to close this milestone, would you like to update team what is the current status of this issue?

**Comment by Vytau** [comment]
still working on it, I will make sure that at the end of the day my issues will be closed

**Comment by obaid22192** [comment]
They both are kind of same but if you still can not manage to close both then close one and move other one to the next milestone(M6).

**Comment by obaid22192** [comment]
mark deleted in directory and delete from content repo.
