### ISSUE TITLE
add api to copy file/folder.

### ISSUE THREAD

**Issue by obaid22192** [projectEP/test#54]
This api will allow user to copy file/folder from one location and paste it to another(inside xxxfileshring). we will not use os clip board, we will build our in strategy to accomplish this task.

**Comment by Abdullahaltuhami** [comment]
### About issue 
Isn’t copying and pasting uses the same method as writing a directory to a file ? Meaning if a user can right to a file then he is already writing to the storage server. Its just a question to clear things out

**Comment by obaid22192** [comment]
I think issue heading was pretty wage, this issue was related to in app copy paste i.e copy one file or folder to another location(inside app). I have added new patch regarding this issue you can have a look at it. 
If you still have question kindly feel free to discuss currently i am closing this issue after reviewing the patch if you still have question kindly reopen this issue with label discussion.
